services:
  web:
    environment:
      - DJANGO_SETTINGS_MODULE=kilsarDjango.settings.prod
      - DJANGO_DEBUG=0
    command: >
      sh -c "python manage.py migrate &&
            gunicorn kilsarDjango.wsgi:application --bind 0.0.0.0:8000"
  celery:
    build: .
    command: celery -A kilsarDjango worker -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=kilsarDjango.settings.prod
    depends_on:
      - redis
      - db
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - web

volumes:
  static_volume: