# Generated by Django 5.2.1 on 2025-05-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_items',
            field=models.ManyToManyField(blank=True, to='todolist.todoitem'),
        ),
    ]
