# Generated by Django 5.2.1 on 2025-05-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_remove_todo_is_complete_todo_todo_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='todo_items',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='todoitem',
            unique_together={('todo_list', 'order')},
        ),
    ]
