# Generated by Django 5.2.1 on 2025-05-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_todoitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
